### PR TITLE
Add LANG files for BLS. Some are "missing".

### PR DESCRIPTION
**Pull request by IcaroKaue**
See https://github.com/GTNewHorizons/GTNH-Translations/issues/8#issuecomment-1987566109 for more context. 

A problem I saw is that some translations are not done (de_DE, ko_KR and ja_JP). Maybe we should wait until they are translated to include them? Nonetheless, the other translations seem to be complete.

### CODE REVIEW

**Comment by boubou19** [comment]
why isn't this covered by the usage of txloader?

**Comment by IcaroKaue** [comment]
Even though we use txloader, it doesn't seem to load in game. Perhaps BLS loads its .lang files before everything else.

**Review by miozune — COMMENTED** [review]
Incomplete translations, including `es_ES` and `fr_FR`, should be excluded. I'll add workaround for the issue with txloader so that everything other than `betterloadingscreen.state.minecraft_init` can be translated with it.

**Comment by IcaroKaue** [comment]
I have removed the incomplete translations. I hope this correctly addresses the issue.

**Review by miozune — APPROVED** [review]

**Pull request merged**
