### PR TITLE
Render on a separate thread, inspired by FML's splash screen implementation

### LINKED ISSUE #10281: Strange strobe on the loading screen
### Your GTNH Discord Username

MuXiu1997#3167

### Your Pack Version

2.1.2.4-dev-pre-test

### Your Server

SP

### Type of Server

_No response_

### Your Expectation

/

### The Reality

image

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by eigenraven**
Removes stuttering, some visual glitches (fixes <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10281>).
Implementation closely follows how `cpw.mods.fml.client.SplashProgress` works, with the SharedDrawable usage, etc. taken from there.

Also removed a second copy of the whole rendering code in the if(blending) part, because it is already drawn by the other code - it was completely useless and caused visual artifacts. 

I tested it locally in the full pack on Linux

### CODE REVIEW

**Comment by MuXiu1997** [comment]
Feedback:
2.1.2.4-pre + M1 Mac

https://user-images.githubusercontent.com/49554020/168478597-a3327a42-311a-4eff-8470-960b9400c594.mp4

**Comment by MuXiu1997** [comment]
Feedback:
2.1.2.4-pre + M1 Mac

https://user-images.githubusercontent.com/49554020/168478597-a3327a42-311a-4eff-8470-960b9400c594.mp4

**Comment by eigenraven** [comment]
@MuXiu1997 can you try the current version?

**Comment by MuXiu1997** [comment]
Seems to work fine

**Comment by Dream-Master** [comment]
works fine for me too.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
